"""
Slack & email notifier for EOL scan results.

Slack uses Block Kit for rich formatting.
Email uses inline HTML (no external images) compatible with most clients.
"""

from __future__ import annotations

import json
import logging
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Optional

import httpx

from scanner.models import EOLResult, EOLStatus, ScanReport

log = logging.getLogger(__name__)

_STATUS_ICONS = {
    EOLStatus.EXPIRED: "🔴",
    EOLStatus.CRITICAL: "🟡",
    EOLStatus.UNKNOWN: "⚪",
    EOLStatus.OK: "🟢",
    EOLStatus.ACTIVE: "🟢",
}


# ---------------------------------------------------------------------------
# Slack
# ---------------------------------------------------------------------------

def send_slack_alert(
    report: ScanReport,
    webhook_url: str,
    ai_summary: Optional[str] = None,
) -> bool:
    at_risk = [r for r in report.results if r.is_at_risk]
    if not at_risk:
        log.info("No at-risk items — skipping Slack alert.")
        return True

    header = f"⚠️ EOL Alert — {len(at_risk)} component(s) require attention"

    lines = []
    for item in at_risk:
        icon = _STATUS_ICONS.get(item.status, "⚪")
        days = f"{item.days_remaining}d" if item.days_remaining >= 0 else "N/A"
        lines.append(
            f"{icon} *{item.name}* `v{item.version}` — EOL: {item.eol_date or 'unknown'} ({days} left)"
        )

    blocks = [
        {
            "type": "header",
            "text": {"type": "plain_text", "text": "🛡️ AIOps Sentinel — EOL Report", "emoji": True},
        },
        {"type": "section", "text": {"type": "mrkdwn", "text": header}},
        {"type": "divider"},
        {"type": "section", "text": {"type": "mrkdwn", "text": "\n".join(lines)}},
    ]

    if ai_summary:
        blocks.append({"type": "divider"})
        blocks.append(
            {"type": "section", "text": {"type": "mrkdwn", "text": f"*🤖 AI Risk Summary*\n{ai_summary}"}}
        )

    blocks.append(
        {
            "type": "context",
            "elements": [{"type": "mrkdwn", "text": f"Scan ID: `{report.scan_id}` • {report.scanned_at}"}],
        }
    )

    try:
        with httpx.Client(timeout=10) as client:
            resp = client.post(
                webhook_url,
                content=json.dumps({"blocks": blocks}),
                headers={"Content-Type": "application/json"},
            )
            if resp.status_code != 200:
                log.error("Slack returned %s: %s", resp.status_code, resp.text)
                return False
        log.info("Slack alert sent — %d at-risk items.", len(at_risk))
        return True
    except Exception as exc:
        log.error("Slack alert failed: %s", exc)
        return False


# ---------------------------------------------------------------------------
# Email
# ---------------------------------------------------------------------------

def _build_html(report: ScanReport, ai_summary: Optional[str] = None) -> str:
    rows = ""
    for item in report.results:
        colour = {
            EOLStatus.EXPIRED: "#ffd6d6",
            EOLStatus.CRITICAL: "#fff3cd",
            EOLStatus.UNKNOWN: "#f0f0f0",
        }.get(item.status, "#d6f5d6")
        days = str(item.days_remaining) if item.days_remaining >= 0 else "—"
        rows += (
            f"<tr style='background:{colour}'>"
            f"<td>{item.name}</td>"
            f"<td>{item.version}</td>"
            f"<td>{item.eol_date or '—'}</td>"
            f"<td>{days}</td>"
            f"<td>{item.status.value.upper()}</td>"
            f"<td>{item.source}</td>"
            "</tr>"
        )

    summary_block = (
        f"<h3>🤖 AI Risk Summary</h3><p>{ai_summary}</p>" if ai_summary else ""
    )

    return f"""<!DOCTYPE html><html><body style="font-family:Arial,sans-serif;max-width:900px;margin:0 auto">
<h2>🛡️ AIOps Sentinel — EOL Scan Report</h2>
<p>Scan ID: <code>{report.scan_id}</code> &nbsp;|&nbsp; {report.scanned_at}</p>
<p><strong>{report.at_risk}</strong> of <strong>{report.total}</strong> components require attention.</p>
{summary_block}
<table border="1" cellpadding="6" cellspacing="0" style="border-collapse:collapse;width:100%">
  <thead style="background:#2c3e50;color:#fff">
    <tr><th>Name</th><th>Version</th><th>EOL Date</th><th>Days Left</th><th>Status</th><th>Source</th></tr>
  </thead>
  <tbody>{rows}</tbody>
</table>
<p style="color:#888;font-size:0.85em;margin-top:20px">Generated by AIOps Sentinel</p>
</body></html>"""


def send_email_alert(
    report: ScanReport,
    smtp_host: str,
    smtp_port: int,
    smtp_user: str,
    smtp_password: str,
    from_addr: str,
    to_addr: str,
    ai_summary: Optional[str] = None,
) -> bool:
    at_risk = [r for r in report.results if r.is_at_risk]
    if not at_risk:
        log.info("No at-risk items — skipping email alert.")
        return True

    msg = MIMEMultipart("alternative")
    msg["From"] = from_addr
    msg["To"] = to_addr
    msg["Subject"] = f"[EOL Alert] {len(at_risk)} component(s) at risk — {report.scanned_at[:10]}"
    msg.attach(MIMEText(_build_html(report, ai_summary), "html"))

    try:
        with smtplib.SMTP(smtp_host, smtp_port) as server:
            server.starttls()
            server.login(smtp_user, smtp_password)
            server.sendmail(from_addr, to_addr, msg.as_string())
        log.info("Email alert sent to %s.", to_addr)
        return True
    except Exception as exc:
        log.error("Email alert failed: %s", exc)
        return False
